language: c
sudo: required
dist: trusty
os: linux
compiler:
  - gcc
notifications:
  email: false
  
script: 
  - sudo ./build.sh 1.11.1
  - [ -e ./vendor/nginx/objs/ngx_http_templarbit_csp_module.so ] && exit 0 || exit 1
