language: c
sudo: required
dist: trusty
os: linux
compiler:
  - gcc
notifications:
  email: false
  
script: 
  - sudo ./build.sh 1.11.1
  - test -e ./vendor/nginx/objs/ngx_http_templarbit_csp_module.so
